version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - cd client
      - yarn install --frozen-lockfile

  build:
    commands:
      - yarn build

artifacts:
  base-directory: client/build
  files:
    - "**/*"
