version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cicd-test
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/appplication_start.sh
      timeout: 300
      runas: ec2-user
      script: |
        source /home/ec2-user/exim-new/scripts/appplication_start.sh
